name: Deploy With Ansible

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python and Ansible
        run: |
          sudo apt update
          sudo apt install python3-pip -y 
          pip3 install ansible

      - name: Add SSH Key file and Set Permissions & add to known_host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Replace Placeholders in my inventory
        run: |
          sed -i "s/{{ host_placeholder }}/${{ secrets.HOST }}/" ansible/inventory.yml
          sed -i "s/{{ user_placeholder }}/${{ secrets.USER }}/" ansible/inventory.yml

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
